"""Add entity and i18n description fields to game_logs

Revision ID: xxx
Revises: yyy
Create Date: YYYY-MM-DD HH:MM:SS.MSMSMS

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'xxx' # Replace with actual new revision ID
down_revision = 'yyy' # Replace with the revision ID of the migration that created game_logs table initially, or the latest migration before this one.
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('game_logs', sa.Column('source_entity_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('game_logs', sa.Column('source_entity_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('game_logs', sa.Column('target_entity_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('game_logs', sa.Column('target_entity_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('game_logs', sa.Column('description_key', sa.VARCHAR(length=255), nullable=True))
    op.add_column('game_logs', sa.Column('description_params_json', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('game_logs', 'description_params_json')
    op.drop_column('game_logs', 'description_key')
    op.drop_column('game_logs', 'target_entity_type')
    op.drop_column('game_logs', 'target_entity_id')
    op.drop_column('game_logs', 'source_entity_type')
    op.drop_column('game_logs', 'source_entity_id')
    # ### end Alembic commands ###
