"""Update generated_quests table and create crafting_recipes table.

Revision ID: ADD_CRAFTING_RECIPES_TABLE # Replace with actual new revision ID
Revises: MAKE_DISCORD_ID_NOT_NULL # Replace with the ID of the Player discord_id nullable migration
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = 'ADD_CRAFTING_RECIPES_TABLE' # Replace with actual new revision ID
down_revision = 'MAKE_DISCORD_ID_NOT_NULL' # Replace with actual previous revision ID
branch_labels = None
depends_on = None

TABLE_GENERATED_QUESTS = 'generated_quests'
TABLE_CRAFTING_RECIPES = 'crafting_recipes'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Update generated_quests table
    op.create_foreign_key(
        'fk_generated_quests_guild_id_guild_configs',  # Constraint name
        TABLE_GENERATED_QUESTS,                        # Source table
        'guild_configs',                               # Target table
        ['guild_id'],                                  # Source columns
        ['guild_id'],                                  # Target columns
        ondelete='CASCADE'
    )

    # 2. Create crafting_recipes table
    op.create_table(
        TABLE_CRAFTING_RECIPES,
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('guild_id', sa.String(), nullable=False),
        sa.Column('name_i18n', JSONB, nullable=False),
        sa.Column('description_i18n', JSONB, nullable=True),
        sa.Column('ingredients_json', JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('output_item_template_id', sa.String(), nullable=False),
        sa.Column('output_quantity', sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column('required_skill_id', sa.String(), nullable=True),
        sa.Column('required_skill_level', sa.Integer(), nullable=True),
        sa.Column('other_requirements_json', JSONB, nullable=True, server_default=sa.text("'{}'::jsonb")),
        sa.Column('ai_metadata_json', JSONB, nullable=True, server_default=sa.text("'{}'::jsonb")),

        sa.PrimaryKeyConstraint('id', name=op.f(f'pk_{TABLE_CRAFTING_RECIPES}')),
        sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_guild_id_guild_configs'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['output_item_template_id'], ['item_templates.id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_output_item_template_id_item_templates')),
        sa.ForeignKeyConstraint(['required_skill_id'], ['skills.id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_required_skill_id_skills'))
    )

    op.create_index(op.f(f'ix_{TABLE_CRAFTING_RECIPES}_guild_id'), TABLE_CRAFTING_RECIPES, ['guild_id'], unique=False) # Index for guild_id FK
    op.create_index('idx_craftingrecipe_guild_output_item', TABLE_CRAFTING_RECIPES, ['guild_id', 'output_item_template_id'], unique=False)
    op.create_index('idx_craftingrecipe_guild_skill', TABLE_CRAFTING_RECIPES, ['guild_id', 'required_skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop crafting_recipes table (indexes and FKs associated with it will be dropped too)
    op.drop_table(TABLE_CRAFTING_RECIPES)

    # 2. Update generated_quests table
    op.drop_constraint('fk_generated_quests_guild_id_guild_configs', TABLE_GENERATED_QUESTS, type_='foreignkey')

    # ### end Alembic commands ###
