"""Update discord_id to be NOT NULL in players table.

Revision ID: MAKE_DISCORD_ID_NOT_NULL # Replace with actual new revision ID
Revises: PREVIOUS_LOCATION_REVISION_ID # Replace with the ID of the Location model migration or latest
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'MAKE_DISCORD_ID_NOT_NULL' # Replace with actual new revision ID
# Ensure this 'down_revision' points to the migration that updated the Location model,
# or the latest relevant migration if that's different.
down_revision = 'NEW_LOCATION_REVISION_ID' # Replace with actual previous revision ID from Location update
branch_labels = None
depends_on = None

TABLE_NAME = 'players'
COLUMN_NAME = 'discord_id'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(TABLE_NAME,
                    COLUMN_NAME,
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(TABLE_NAME,
                    COLUMN_NAME,
                    existing_type=sa.String(),
                    nullable=True)
    # ### end Alembic commands ###
