"""Add party_id to players and template_id to locations

Revision ID: 20240315_add_party_template_ids
Revises:
Create Date: 2024-03-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20240315_add_party_template_ids'
down_revision = None  # Assuming no prior relevant migration or starting fresh for these
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('party_id', sa.String(), sa.ForeignKey('parties.id'), nullable=True))
    op.add_column('locations', sa.Column('template_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'template_id')
    op.drop_column('players', 'party_id')
    # ### end Alembic commands ###
