"""Add skills_data_equipment_data_abilities_data_faction_behavior_tags_loot_table_id_to_npcs

Revision ID: 0d1b1948d058
Revises: 7a59d7dc8026
Create Date: 2025-06-07 00:57:33.126362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1b1948d058'
down_revision: Union[str, None] = '7a59d7dc8026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('equipment_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('abilities_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('faction', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('behavior_tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('loot_table_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.drop_column('loot_table_id')
        batch_op.drop_column('behavior_tags')
        batch_op.drop_column('faction')
        batch_op.drop_column('abilities_data')
        batch_op.drop_column('equipment_data')
        batch_op.drop_column('skills_data')

    # ### end Alembic commands ###
