"""add_generated_details_to_location

Revision ID: 202401010001
Revises: d9dbc4f4caa8
Create Date: 2024-01-01 00:01:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202401010001'
down_revision: Union[str, None] = 'd9dbc4f4caa8' # Замените на ID предыдущей миграции, если он известен, иначе None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('generated_details_json', postgresql.JSONB(astext_fallback=True), nullable=True, comment='Additional AI-generated descriptive details for the location'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'generated_details_json')
    # ### end Alembic commands ###
