"""Make players.discord_id not nullable

Revision ID: 3d4e5f0a1b2c
Revises: 2c3d4e5f0a1b
Create Date: YYYY-MM-DD HH:MM:SS.MSMSMS # Placeholder, Alembic updates this

"""
from typing import Sequence, Union # Added for consistency
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3d4e5f0a1b2c'
down_revision: Union[str, None] = '2c3d4e5f0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_NAME = 'players'
COLUMN_NAME = 'discord_id'

def upgrade() -> None: # Added type hint
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(TABLE_NAME,
                    COLUMN_NAME,
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None: # Added type hint
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(TABLE_NAME,
                    COLUMN_NAME,
                    existing_type=sa.String(),
                    nullable=True)
    # ### end Alembic commands ###
