"""Update generated_quests table and create crafting_recipes table.

Revision ID: 4e5f0a1b2c3d
Revises: 3d4e5f0a1b2c
Create Date: YYYY-MM-DD HH:MM:SS.MS # Placeholder, Alembic updates this

"""
from typing import Sequence, Union # Added for consistency
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '4e5f0a1b2c3d'
down_revision: Union[str, None] = '3d4e5f0a1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_GENERATED_QUESTS = 'generated_quests'
TABLE_CRAFTING_RECIPES = 'crafting_recipes'

def upgrade() -> None: # Added type hint
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Update generated_quests table
    op.create_foreign_key(
        'fk_generated_quests_guild_id_guild_configs',  # Constraint name
        TABLE_GENERATED_QUESTS,                        # Source table
        'guild_configs',                               # Target table
        ['guild_id'],                                  # Source columns
        ['guild_id'],                                  # Target columns
        ondelete='CASCADE'
    )

    # 2. Create crafting_recipes table
    op.create_table(
        TABLE_CRAFTING_RECIPES,
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('guild_id', sa.String(), nullable=False),
        sa.Column('name_i18n', JSONB, nullable=False),
        sa.Column('description_i18n', JSONB, nullable=True),
        sa.Column('ingredients_json', JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('output_item_template_id', sa.String(), nullable=False),
        sa.Column('output_quantity', sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column('required_skill_id', sa.String(), nullable=True),
        sa.Column('required_skill_level', sa.Integer(), nullable=True),
        sa.Column('other_requirements_json', JSONB, nullable=True, server_default=sa.text("'{}'::jsonb")),
        sa.Column('ai_metadata_json', JSONB, nullable=True, server_default=sa.text("'{}'::jsonb")),

        sa.PrimaryKeyConstraint('id', name=op.f(f'pk_{TABLE_CRAFTING_RECIPES}')),
        sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_guild_id_guild_configs'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['output_item_template_id'], ['item_templates.id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_output_item_template_id_item_templates')),
        sa.ForeignKeyConstraint(['required_skill_id'], ['skills.id'], name=op.f(f'fk_{TABLE_CRAFTING_RECIPES}_required_skill_id_skills'))
    )

    op.create_index(op.f(f'ix_{TABLE_CRAFTING_RECIPES}_guild_id'), TABLE_CRAFTING_RECIPES, ['guild_id'], unique=False)
    op.create_index('idx_craftingrecipe_guild_output_item', TABLE_CRAFTING_RECIPES, ['guild_id', 'output_item_template_id'], unique=False)
    op.create_index('idx_craftingrecipe_guild_skill', TABLE_CRAFTING_RECIPES, ['guild_id', 'required_skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None: # Added type hint
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop crafting_recipes table (indexes and FKs associated with it will be dropped too)
    op.drop_table(TABLE_CRAFTING_RECIPES)

    # 2. Update generated_quests table
    op.drop_constraint('fk_generated_quests_guild_id_guild_configs', TABLE_GENERATED_QUESTS, type_='foreignkey')

    # ### end Alembic commands ###
