"""create_all_tables

Revision ID: 5c3a0b7555c0
Revises: 
Create Date: 2025-06-06 17:56:25.385109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3a0b7555c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crafting_queues',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('queue', sa.JSON(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id', 'entity_type', 'guild_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('current_stage_id', sa.String(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('stages_data', sa.JSON(), nullable=True),
    sa.Column('end_message_template', sa.Text(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_factions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_npcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_quests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('item_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('static_name', sa.String(), nullable=True),
    sa.Column('descriptions_i18n', sa.JSON(), nullable=True),
    sa.Column('static_connections', sa.JSON(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=True),
    sa.Column('current_location_id', sa.String(), nullable=True),
    sa.Column('turn_status', sa.String(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('leader_id', sa.String(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('current_action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_npc_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_location_id', sa.String(), nullable=True),
    sa.Column('selected_language', sa.String(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('unspent_xp', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('current_game_status', sa.String(), nullable=True),
    sa.Column('collected_actions_json', sa.JSON(), nullable=True),
    sa.Column('current_party_id', sa.String(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('current_action', sa.String(), nullable=True),
    sa.Column('action_queue', sa.JSON(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('max_health', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('skills_data_json', sa.JSON(), nullable=True),
    sa.Column('abilities_data_json', sa.JSON(), nullable=True),
    sa.Column('spells_data_json', sa.JSON(), nullable=True),
    sa.Column('character_class', sa.String(), nullable=True),
    sa.Column('flags_json', sa.JSON(), nullable=True),
    sa.Column('active_quests', sa.JSON(), nullable=True),
    sa.Column('known_spells', sa.JSON(), nullable=True),
    sa.Column('spell_cooldowns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['current_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('duration_turns', sa.Integer(), nullable=True),
    sa.Column('applied_at_time', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('combat_log', sa.Text(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('turn_order', sa.JSON(), nullable=True),
    sa.Column('current_turn_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('name_i18n', sa.JSON(), nullable=True),
    sa.Column('description_i18n', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('name_i18n', sa.JSON(), nullable=True),
    sa.Column('description_i18n', sa.JSON(), nullable=True),
    sa.Column('backstory_i18n', sa.JSON(), nullable=True),
    sa.Column('persona_i18n', sa.JSON(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('current_action', sa.String(), nullable=True),
    sa.Column('action_queue', sa.JSON(), nullable=True),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('state_variables', sa.JSON(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('max_health', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=True),
    sa.Column('archetype', sa.String(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('desires', sa.JSON(), nullable=True),
    sa.Column('motives', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('npcs')
    op.drop_table('items')
    op.drop_table('combats')
    op.drop_table('statuses')
    op.drop_table('skills')
    op.drop_table('rules_config')
    op.drop_table('relationships')
    op.drop_table('questlines')
    op.drop_table('quest_steps')
    op.drop_table('players')
    op.drop_table('player_npc_memory')
    op.drop_table('parties')
    op.drop_table('mobile_groups')
    op.drop_table('logs')
    op.drop_table('locations')
    op.drop_table('location_templates')
    op.drop_table('item_properties')
    op.drop_table('global_state')
    op.drop_table('generated_quests')
    op.drop_table('generated_npcs')
    op.drop_table('generated_locations')
    op.drop_table('generated_factions')
    op.drop_table('events')
    op.drop_table('crafting_queues')
    op.drop_table('abilities')
    # ### end Alembic commands ###
