"""Add party_id to players table if missing

Revision ID: 7a59d7dc8026
Revises: 14bff409174f
Create Date: 2025-06-07 00:47:46.802886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a59d7dc8026'
down_revision: Union[str, None] = '14bff409174f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_players')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_players_party_id_parties', 'parties', ['party_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_players')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_party_id_parties', type_='foreignkey')
        batch_op.drop_column('party_id')

    # ### end Alembic commands ###
