"""add state_variables to locations

Revision ID: 7d887g92h0f2
Revises: 6d887g92h0f1
Create Date: YYYY-MM-DD HH:MM:SS.mmmmmm

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7d887g92h0f2'
down_revision = '6d887g92h0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('state_variables', sa.JSON(), server_default=sa.text("'{}'"), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'state_variables')
    # ### end Alembic commands ###
