"""add_effective_stats_to_player_and_npc_and_adjust_types

Revision ID: a763bbe776c0
Revises: b8227c54d16b
Create Date: 2025-06-12 00:19:00.506506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a763bbe776c0'
down_revision: Union[str, None] = 'b8227c54d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually adjusted ###
    # effective_stats_json columns were found to be already in the initial schema (b8227c54d16b)
    # This migration will now focus on type adjustments.

    # Player table type adjustments
    op.alter_column('players', 'hp',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('players', 'max_health',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)

    # NPC table type adjustments
    op.alter_column('npcs', 'health',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('npcs', 'max_health',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)

    # Statuses table type adjustments
    op.alter_column('statuses', 'duration_turns',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('statuses', 'applied_at',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               nullable=True)

    # Note: current_action fields were already String in initial schema, matching model.
    # No op.add_column needed for effective_stats_json as they were in the initial migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - manually adjusted ###
    # Statuses table type adjustments (revert)
    op.alter_column('statuses', 'applied_at',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('statuses', 'duration_turns',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)

    # NPC table type adjustments (revert)
    op.alter_column('npcs', 'max_health',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('npcs', 'health',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)

    # Player table type adjustments (revert)
    op.alter_column('players', 'max_health',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('players', 'hp',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               nullable=True)

    # No op.drop_column needed for effective_stats_json as they were in the initial migration.
    # ### end Alembic commands ###
