"""add_guild_id_to_models_and_updates

Revision ID: c1a3b2d4e5f6
Revises: b8227c54d16b
Create Date: 2024-07-26 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c1a3b2d4e5f6'
down_revision: Union[str, None] = 'b8227c54d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. rules_config
    op.drop_table('rules_config')
    op.create_table('rules_config',
        sa.Column('guild_id', sa.String(), nullable=False),
        sa.Column('config_data', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('guild_id')
    )

    # 2. generated_locations
    op.add_column('generated_locations', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('generated_locations', 'guild_id', server_default=None)
    op.create_index('idx_generatedlocation_guild_id', 'generated_locations', ['guild_id'], unique=False)

    # 3. item_templates
    op.alter_column('item_templates', 'guild_id', existing_type=sa.String(), nullable=False, server_default='NEEDS_UPDATE')
    op.alter_column('item_templates', 'guild_id', server_default=None)
    op.create_index('idx_itemtemplate_guild_id', 'item_templates', ['guild_id'], unique=False)

    # 4. generated_npcs
    op.add_column('generated_npcs', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('generated_npcs', 'guild_id', server_default=None)
    op.create_index('idx_generatednpc_guild_id', 'generated_npcs', ['guild_id'], unique=False)

    # 5. generated_factions
    op.drop_column('generated_factions', 'placeholder')
    op.add_column('generated_factions', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('generated_factions', 'guild_id', server_default=None)
    op.add_column('generated_factions', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.add_column('generated_factions', sa.Column('description_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_generatedfaction_guild_id', 'generated_factions', ['guild_id'], unique=False)

    # 6. generated_quests
    op.drop_column('generated_quests', 'placeholder')
    op.add_column('generated_quests', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('generated_quests', 'guild_id', server_default=None)
    op.add_column('generated_quests', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_generatedquest_guild_id', 'generated_quests', ['guild_id'], unique=False)

    # 7. items
    op.alter_column('items', 'guild_id', existing_type=sa.String(), nullable=False, server_default='NEEDS_UPDATE')
    op.alter_column('items', 'guild_id', server_default=None)
    op.create_index('idx_item_guild_id', 'items', ['guild_id'], unique=False)

    # 8. relationships
    op.drop_column('relationships', 'placeholder')
    op.add_column('relationships', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('relationships', 'guild_id', server_default=None)
    op.add_column('relationships', sa.Column('entity1_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('relationships', 'entity1_id', server_default=None)
    op.add_column('relationships', sa.Column('entity1_type', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('relationships', 'entity1_type', server_default=None)
    op.add_column('relationships', sa.Column('entity2_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('relationships', 'entity2_id', server_default=None)
    op.add_column('relationships', sa.Column('entity2_type', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('relationships', 'entity2_type', server_default=None)
    op.add_column('relationships', sa.Column('relationship_type_i18n', sa.JSON(), nullable=True))
    op.add_column('relationships', sa.Column('status_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_relationship_guild_id', 'relationships', ['guild_id'], unique=False)

    # 9. player_npc_memory
    op.drop_column('player_npc_memory', 'placeholder')
    op.add_column('player_npc_memory', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('player_npc_memory', 'guild_id', server_default=None)
    op.add_column('player_npc_memory', sa.Column('player_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('player_npc_memory', 'player_id', server_default=None)
    op.add_column('player_npc_memory', sa.Column('npc_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('player_npc_memory', 'npc_id', server_default=None)
    op.add_column('player_npc_memory', sa.Column('memory_details_i18n', sa.JSON(), nullable=True))
    op.create_foreign_key('fk_player_npc_memory_player_id', 'player_npc_memory', 'players', ['player_id'], ['id'])
    op.create_foreign_key('fk_player_npc_memory_npc_id', 'player_npc_memory', 'npcs', ['npc_id'], ['id'])
    op.create_index('idx_playernpcmemory_guild_id', 'player_npc_memory', ['guild_id'], unique=False)
    op.create_index('idx_playernpcmemory_player_id', 'player_npc_memory', ['player_id'], unique=False)
    op.create_index('idx_playernpcmemory_npc_id', 'player_npc_memory', ['npc_id'], unique=False)

    # 10. abilities
    op.add_column('abilities', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('abilities', 'guild_id', server_default=None)
    op.add_column('abilities', sa.Column('effect_i18n', sa.JSON(), nullable=True))
    op.add_column('abilities', sa.Column('cost', sa.JSON(), nullable=True))
    op.add_column('abilities', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('abilities', sa.Column('type_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_ability_guild_id', 'abilities', ['guild_id'], unique=False)

    # 11. skills
    op.add_column('skills', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('skills', 'guild_id', server_default=None)
    op.create_index('idx_skill_guild_id', 'skills', ['guild_id'], unique=False)

    # 12. item_properties
    op.add_column('item_properties', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('item_properties', 'guild_id', server_default=None)
    op.create_index('idx_itemproperty_guild_id', 'item_properties', ['guild_id'], unique=False)

    # 13. questlines
    op.drop_column('questlines', 'placeholder')
    op.add_column('questlines', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('questlines', 'guild_id', server_default=None)
    op.add_column('questlines', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_questline_guild_id', 'questlines', ['guild_id'], unique=False)

    # 14. quest_steps
    op.drop_column('quest_steps', 'placeholder')
    op.add_column('quest_steps', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('quest_steps', 'guild_id', server_default=None)
    op.add_column('quest_steps', sa.Column('questline_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('quest_steps', 'questline_id', server_default=None)
    op.add_column('quest_steps', sa.Column('step_details_i18n', sa.JSON(), nullable=True))
    op.create_foreign_key('fk_quest_steps_questline_id', 'quest_steps', 'questlines', ['questline_id'], ['id'])
    op.create_index('idx_queststep_guild_id', 'quest_steps', ['guild_id'], unique=False)
    op.create_index('idx_queststep_questline_id', 'quest_steps', ['questline_id'], unique=False)

    # 15. mobile_groups
    op.drop_column('mobile_groups', 'placeholder')
    op.add_column('mobile_groups', sa.Column('guild_id', sa.String(), nullable=False, server_default='NEEDS_UPDATE'))
    op.alter_column('mobile_groups', 'guild_id', server_default=None)
    op.add_column('mobile_groups', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.create_index('idx_mobilegroup_guild_id', 'mobile_groups', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 15. mobile_groups
    op.drop_index('idx_mobilegroup_guild_id', table_name='mobile_groups')
    op.drop_column('mobile_groups', 'name_i18n')
    op.drop_column('mobile_groups', 'guild_id')
    op.add_column('mobile_groups', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 14. quest_steps
    op.drop_index('idx_queststep_questline_id', table_name='quest_steps')
    op.drop_index('idx_queststep_guild_id', table_name='quest_steps')
    op.drop_constraint('fk_quest_steps_questline_id', 'quest_steps', type_='foreignkey')
    op.drop_column('quest_steps', 'step_details_i18n')
    op.drop_column('quest_steps', 'questline_id')
    op.drop_column('quest_steps', 'guild_id')
    op.add_column('quest_steps', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 13. questlines
    op.drop_index('idx_questline_guild_id', table_name='questlines')
    op.drop_column('questlines', 'name_i18n')
    op.drop_column('questlines', 'guild_id')
    op.add_column('questlines', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 12. item_properties
    op.drop_index('idx_itemproperty_guild_id', table_name='item_properties')
    op.drop_column('item_properties', 'guild_id')

    # 11. skills
    op.drop_index('idx_skill_guild_id', table_name='skills')
    op.drop_column('skills', 'guild_id')

    # 10. abilities
    op.drop_index('idx_ability_guild_id', table_name='abilities')
    op.drop_column('abilities', 'type_i18n')
    op.drop_column('abilities', 'requirements')
    op.drop_column('abilities', 'cost')
    op.drop_column('abilities', 'effect_i18n')
    op.drop_column('abilities', 'guild_id')

    # 9. player_npc_memory
    op.drop_index('idx_playernpcmemory_npc_id', table_name='player_npc_memory')
    op.drop_index('idx_playernpcmemory_player_id', table_name='player_npc_memory')
    op.drop_index('idx_playernpcmemory_guild_id', table_name='player_npc_memory')
    op.drop_constraint('fk_player_npc_memory_npc_id', 'player_npc_memory', type_='foreignkey')
    op.drop_constraint('fk_player_npc_memory_player_id', 'player_npc_memory', type_='foreignkey')
    op.drop_column('player_npc_memory', 'memory_details_i18n')
    op.drop_column('player_npc_memory', 'npc_id')
    op.drop_column('player_npc_memory', 'player_id')
    op.drop_column('player_npc_memory', 'guild_id')
    op.add_column('player_npc_memory', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 8. relationships
    op.drop_index('idx_relationship_guild_id', table_name='relationships')
    op.drop_column('relationships', 'status_i18n')
    op.drop_column('relationships', 'relationship_type_i18n')
    op.drop_column('relationships', 'entity2_type')
    op.drop_column('relationships', 'entity2_id')
    op.drop_column('relationships', 'entity1_type')
    op.drop_column('relationships', 'entity1_id')
    op.drop_column('relationships', 'guild_id')
    op.add_column('relationships', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 7. items
    op.drop_index('idx_item_guild_id', table_name='items')
    op.alter_column('items', 'guild_id', existing_type=sa.String(), nullable=True) # Make nullable again

    # 6. generated_quests
    op.drop_index('idx_generatedquest_guild_id', table_name='generated_quests')
    op.drop_column('generated_quests', 'name_i18n')
    op.drop_column('generated_quests', 'guild_id')
    op.add_column('generated_quests', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 5. generated_factions
    op.drop_index('idx_generatedfaction_guild_id', table_name='generated_factions')
    op.drop_column('generated_factions', 'description_i18n')
    op.drop_column('generated_factions', 'name_i18n')
    op.drop_column('generated_factions', 'guild_id')
    op.add_column('generated_factions', sa.Column('placeholder', sa.TEXT(), autoincrement=False, nullable=True))

    # 4. generated_npcs
    op.drop_index('idx_generatednpc_guild_id', table_name='generated_npcs')
    op.drop_column('generated_npcs', 'guild_id')

    # 3. item_templates
    op.drop_index('idx_itemtemplate_guild_id', table_name='item_templates')
    op.alter_column('item_templates', 'guild_id', existing_type=sa.String(), nullable=True) # Make nullable again

    # 2. generated_locations
    op.drop_index('idx_generatedlocation_guild_id', table_name='generated_locations')
    op.drop_column('generated_locations', 'guild_id')

    # 1. rules_config
    op.drop_table('rules_config')
    op.create_table('rules_config',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('config_data', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='rules_config_pkey') # Explicit PK name for downgrade
    )
    # ### end Alembic commands ###
