"""update_models_remove_placeholder_add_fields

Revision ID: dbe9815c6502
Revises: b502a7aace97
Create Date: 2025-06-14 10:50:25.721615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe9815c6502'
down_revision: Union[str, None] = 'b502a7aace97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_factions', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.add_column('generated_factions', sa.Column('description_i18n', sa.JSON(), nullable=True))
    # op.add_column('generated_factions', sa.Column('guild_id', sa.String(), nullable=False))
    # op.create_index(op.f('ix_generated_factions_guild_id'), 'generated_factions', ['guild_id'], unique=False)
    # op.drop_column('generated_factions', 'placeholder') # Assuming placeholder was to be dropped

    op.add_column('generated_quests', sa.Column('name_i18n', sa.JSON(), nullable=True))
    op.add_column('generated_quests', sa.Column('description_i18n', sa.JSON(), nullable=True))
    # op.add_column('generated_quests', sa.Column('guild_id', sa.String(), nullable=False))
    # op.create_index(op.f('ix_generated_quests_guild_id'), 'generated_quests', ['guild_id'], unique=False)
    # op.drop_column('generated_quests', 'placeholder')

    op.add_column('mobile_groups', sa.Column('name_i18n', sa.JSON(), nullable=True))
    # op.add_column('mobile_groups', sa.Column('guild_id', sa.String(), nullable=False))
    # op.create_index(op.f('ix_mobile_groups_guild_id'), 'mobile_groups', ['guild_id'], unique=False)
    # op.drop_column('mobile_groups', 'placeholder')

    # op.add_column('player_npc_memory', sa.Column('guild_id', sa.String(), nullable=False))
    op.add_column('player_npc_memory', sa.Column('player_id', sa.String(), nullable=False))
    op.add_column('player_npc_memory', sa.Column('npc_id', sa.String(), nullable=False))
    op.add_column('player_npc_memory', sa.Column('memory_details_i18n', sa.JSON(), nullable=True))
    # op.create_index(op.f('ix_player_npc_memory_guild_id'), 'player_npc_memory', ['guild_id'], unique=False)
    # op.create_index(op.f('ix_player_npc_memory_npc_id'), 'player_npc_memory', ['npc_id'], unique=False)
    # op.create_index(op.f('ix_player_npc_memory_player_id'), 'player_npc_memory', ['player_id'], unique=False)
    op.create_foreign_key(None, 'player_npc_memory', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'player_npc_memory', 'npcs', ['npc_id'], ['id'])
    # op.drop_column('player_npc_memory', 'placeholder')

    # op.add_column('quest_steps', sa.Column('guild_id', sa.String(), nullable=False))
    op.add_column('quest_steps', sa.Column('questline_id', sa.String(), nullable=False))
    op.add_column('quest_steps', sa.Column('step_details_i18n', sa.JSON(), nullable=True))
    # op.create_index(op.f('ix_quest_steps_guild_id'), 'quest_steps', ['guild_id'], unique=False)
    op.create_index(op.f('ix_quest_steps_questline_id'), 'quest_steps', ['questline_id'], unique=False)
    op.create_foreign_key(None, 'quest_steps', 'questlines', ['questline_id'], ['id'])
    # op.drop_column('quest_steps', 'placeholder')

    # op.add_column('relationships', sa.Column('guild_id', sa.String(), nullable=False))
    op.add_column('relationships', sa.Column('entity1_id', sa.String(), nullable=False))
    op.add_column('relationships', sa.Column('entity1_type', sa.String(), nullable=False))
    op.add_column('relationships', sa.Column('entity2_id', sa.String(), nullable=False))
    op.add_column('relationships', sa.Column('entity2_type', sa.String(), nullable=False))
    op.add_column('relationships', sa.Column('relationship_type_i18n', sa.JSON(), nullable=True))
    op.add_column('relationships', sa.Column('status_i18n', sa.JSON(), nullable=True))
    # op.create_index(op.f('ix_relationships_guild_id'), 'relationships', ['guild_id'], unique=False)
    op.create_index(op.f('ix_relationships_entity1_id_entity1_type'), 'relationships', ['entity1_id', 'entity1_type'], unique=False)
    op.create_index(op.f('ix_relationships_entity2_id_entity2_type'), 'relationships', ['entity2_id', 'entity2_type'], unique=False)
    # op.drop_column('relationships', 'placeholder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('relationships', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_relationships_entity2_id_entity2_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_entity1_id_entity1_type'), table_name='relationships')
    # op.drop_index(op.f('ix_relationships_guild_id'), table_name='relationships')
    op.drop_column('relationships', 'status_i18n')
    op.drop_column('relationships', 'relationship_type_i18n')
    op.drop_column('relationships', 'entity2_type')
    op.drop_column('relationships', 'entity2_id')
    op.drop_column('relationships', 'entity1_type')
    op.drop_column('relationships', 'entity1_id')
    # op.drop_column('relationships', 'guild_id')

    # op.add_column('quest_steps', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quest_steps', type_='foreignkey')
    op.drop_index(op.f('ix_quest_steps_questline_id'), table_name='quest_steps')
    # op.drop_index(op.f('ix_quest_steps_guild_id'), table_name='quest_steps')
    op.drop_column('quest_steps', 'step_details_i18n')
    op.drop_column('quest_steps', 'questline_id')
    # op.drop_column('quest_steps', 'guild_id')

    # op.add_column('player_npc_memory', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player_npc_memory', type_='foreignkey')
    op.drop_constraint(None, 'player_npc_memory', type_='foreignkey')
    # op.drop_index(op.f('ix_player_npc_memory_player_id'), table_name='player_npc_memory')
    # op.drop_index(op.f('ix_player_npc_memory_npc_id'), table_name='player_npc_memory')
    # op.drop_index(op.f('ix_player_npc_memory_guild_id'), table_name='player_npc_memory')
    op.drop_column('player_npc_memory', 'memory_details_i18n')
    op.drop_column('player_npc_memory', 'npc_id')
    op.drop_column('player_npc_memory', 'player_id')
    # op.drop_column('player_npc_memory', 'guild_id')

    # op.add_column('mobile_groups', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_mobile_groups_guild_id'), table_name='mobile_groups')
    # op.drop_column('mobile_groups', 'guild_id')
    op.drop_column('mobile_groups', 'name_i18n')

    # op.add_column('generated_quests', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_generated_quests_guild_id'), table_name='generated_quests')
    # op.drop_column('generated_quests', 'guild_id')
    op.drop_column('generated_quests', 'description_i18n')
    op.drop_column('generated_quests', 'name_i18n')

    # op.add_column('generated_factions', sa.Column('placeholder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_generated_factions_guild_id'), table_name='generated_factions')
    # op.drop_column('generated_factions', 'guild_id')
    op.drop_column('generated_factions', 'description_i18n')
    op.drop_column('generated_factions', 'name_i18n')
    # ### end Alembic commands ###
