"""Initial schema based on current models

Revision ID: ebfcb0e24979
Revises: 
Create Date: 2025-06-22 06:54:50.649941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebfcb0e24979'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_factions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ideology_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leader_concept_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_notes_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Stores metadata from AI generation, like prompt details or model version'),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generatedfaction_guild_id', 'generated_factions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_generated_factions_guild_id'), 'generated_factions', ['guild_id'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('effect_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spell_guild_id', 'spells', ['guild_id'], unique=False)
    op.create_index(op.f('ix_spells_guild_id'), 'spells', ['guild_id'], unique=False)
    op.drop_index(op.f('ix_players_discord_id'), table_name='players')
    op.create_index(op.f('ix_players_discord_id'), 'players', ['discord_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_discord_id'), table_name='players')
    op.create_index(op.f('ix_players_discord_id'), 'players', ['discord_id'], unique=True)
    op.drop_index(op.f('ix_spells_guild_id'), table_name='spells')
    op.drop_index('idx_spell_guild_id', table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_generated_factions_guild_id'), table_name='generated_factions')
    op.drop_index('idx_generatedfaction_guild_id', table_name='generated_factions')
    op.drop_table('generated_factions')
    # ### end Alembic commands ###
