"""initial_schema_corrected

Revision ID: fd740b26ce51
Revises: 
Create Date: 2025-06-05 11:42:43.657428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd740b26ce51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_factions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_npcs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_quests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('static_name', sa.String(), nullable=True),
    sa.Column('descriptions_i18n', sa.JSON(), nullable=True),
    sa.Column('static_connections', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_npc_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('parties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=True),
    sa.Column('player_ids', sa.JSON(), nullable=True),
    sa.Column('current_location_id', sa.String(), nullable=True),
    sa.Column('turn_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_location_id', sa.String(), nullable=True),
    sa.Column('selected_language', sa.String(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('unspent_xp', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('current_game_status', sa.String(), nullable=True),
    sa.Column('collected_actions_json', sa.JSON(), nullable=True),
    sa.Column('current_party_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['current_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('placeholder', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('players')
    op.drop_table('parties')
    op.drop_table('world_state')
    op.drop_table('statuses')
    op.drop_table('skills')
    op.drop_table('rules_config')
    op.drop_table('relationships')
    op.drop_table('questlines')
    op.drop_table('quest_steps')
    op.drop_table('player_npc_memory')
    op.drop_table('mobile_groups')
    op.drop_table('logs')
    op.drop_table('locations')
    op.drop_table('items')
    op.drop_table('item_properties')
    op.drop_table('generated_quests')
    op.drop_table('generated_npcs')
    op.drop_table('generated_locations')
    op.drop_table('generated_factions')
    op.drop_table('abilities')
    # ### end Alembic commands ###
