"""update_players_add_parties_table

Revision ID: 37b8a174fa4c
Revises: 166034bced80 # Points to 'add_locations_table'
Create Date: 2025-06-16 16:45:30.000000 # Placeholder

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37b8a174fa4c'
down_revision = '166034bced80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to players table
    op.add_column('players', sa.Column('current_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_players_current_location_id_locations'), 'players', 'locations', ['current_location_id'], ['id'])

    op.add_column('players', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('players', sa.Column('unspent_xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('gold', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('players', sa.Column('current_status', sa.Text(), nullable=False, server_default='active'))
    op.add_column('players', sa.Column('collected_actions_json', sa.JSON(), nullable=True, server_default=sa.text("'{}'::json")))
    op.add_column('players', sa.Column('current_party_id', sa.Integer(), nullable=True))
    # Note: FK for current_party_id to 'parties.id' will be created after 'parties' table is defined.
    # For now, just adding the column. Alembic might handle this ordering if parties is created first,
    # or a separate alter_table might be needed if players is altered before parties exists.
    # The provided Party model FK uses 'parties.id', so this table must exist.

    # Create parties table
    op.create_table('parties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('leader_id', sa.Integer(), nullable=False),
        sa.Column('player_ids_json', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
        sa.Column('current_location_id', sa.Integer(), nullable=True),
        sa.Column('turn_status', sa.Text(), nullable=False, server_default='pending_actions'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_parties')),
        sa.ForeignKeyConstraint(['leader_id'], ['players.id'], name=op.f('fk_parties_leader_id_players')),
        sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('fk_parties_current_location_id_locations'))
    )
    op.create_index(op.f('ix_parties_guild_id'), 'parties', ['guild_id'], unique=False)
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False) # Standard PK index

    # Now, add the foreign key from players.current_party_id to parties.id
    # This assumes that the 'parties' table is created before this step if run in a single pass.
    # If Alembic splits operations, this might need to be in a separate `op.alter_column`.
    # For simplicity in manual script, assuming direct creation works if table order is correct.
    op.create_foreign_key(op.f('fk_players_current_party_id_parties'), 'players', 'parties', ['current_party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_players_current_party_id_parties'), 'players', type_='foreignkey')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_guild_id'), table_name='parties')
    op.drop_table('parties')

    op.drop_constraint(op.f('fk_players_current_location_id_locations'), 'players', type_='foreignkey')
    op.drop_column('players', 'current_party_id')
    op.drop_column('players', 'collected_actions_json')
    op.drop_column('players', 'current_status')
    op.drop_column('players', 'gold')
    op.drop_column('players', 'unspent_xp')
    op.drop_column('players', 'level')
    op.drop_column('players', 'xp')
    op.drop_column('players', 'current_location_id')
    # ### end Alembic commands ###
